# {name} = player's ingame name.
# Written by maplesauce.

default:
  - '/message {name} Hey! Welcome back!'

member:
  - '/eco give {name} 1000'
  - '/message {name} Welcome back! You have been given $1,000.'

donator:
  - '/eco give {name} 5000'
  - '/message {name} Welcome back! You have been given $5,000 for being a donator..'
  - '/message {name} This is an extra line!'